### ISSUE TITLE
Idea: interactive doc/article about `rid3`

### ISSUE THREAD

**Issue by viebel** [gadfly361/rid3#1]
You could create an interactive article demonstrating the power of `rid3` using the Klipse plugin.

Here is a [demo](http://blog.klipse.tech/reagent/2016/12/31/reagent-in-klipse.html) of how to create interactive reagent snippets with Klipse.

**Comment by gadfly361** [comment]
@viebel That is a fantastic idea! Will give it a go when I have some time.

**Comment by gadfly361** [comment]
This is a good idea, and if anyone reading this thread wants to make a post, that would be greatly appreciated! For now, I think the live demo examples suffice in showing what rid3 can do.
