### ISSUE TITLE
feature request: For performance reason, add a path options on the pieces

### ISSUE THREAD

**Issue by davidpham87** [gadfly361/rid3#15]
Hello,

The library is really good. However, I get into performance issue. I am trying to implement some behavior using the voronoi layout.

Say you have 10 000s of points and you want to make one point bigger, then given the actual API, I did not manage to only update the requested point, and the library always recompute everything.

Would you have a solution for that problem?

Best regards,
David

**Comment by gadfly361** [comment]
@davidpham87 I'd be happy to look in to it. Can you provide a working, minimal example of what you are currently trying with rid3? Additionally, if you are working off of a d3 example in JavaScript, could you provide a link to that as well.

**Comment by gadfly361** [comment]
@davidpham87 ping

**Comment by gadfly361** [comment]
Since I haven't heard anything, I am going to close this issue.
